spring:
  application:
    name: InventarioBackend

  profiles:
    active: dev

  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"